#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive
apt install -y apache2 msmtp-mta nagios4 rsync s-nail sudo

a2enmod auth_digest
install -C -m644 nagios4-cgi.conf -t /etc/apache2/conf-enabled/

install -C -m640 -o nagios -g www-data secrets/htdigest.users -t /etc/nagios4/
install -C -m600 -o nagios secrets/msmtprc -t /etc/nagios4/
rsync -avh nagios/ /etc/nagios4/

systemctl restart apache2 nagios4

install -m750 -d /etc/sudoers.d
install -C -m 600 sudoers.d/* /etc/sudoers.d

if ! getent passwd nagios-cmd-writer >/dev/null; then
	useradd -r -s /opt/rchain-nagios/sudo-write-nagios-cmd nagios-cmd-writer
fi
