#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive
apt install -y apache2 msmtp-mta nagios4
a2enmod auth_digest
install -C -m644 nagios4-cgi.conf -t /etc/apache2/conf-enabled/
install -C -m640 -o nagios -g www-data secrets/htdigest.users -t /etc/nagios4/
install -C -m600 -o nagios secrets/msmtprc -t /etc/nagios4/
install -C -m644 nagios/hosts-devnet.cfg -t /etc/nagios4/conf.d/
install -C -m644 nagios/hosts-testnet.cfg -t /etc/nagios4/conf.d/
systemctl restart apache2 nagios4
